// examples/solid-base-2/src/context.tsx
import { children, JSXElement } from "solid-js";
import { QueryClient, QueryClientProvider } from "@tanstack/solid-query";

const queryClient = new QueryClient();

type Props = { children: JSXElement };

export function AppProviders(props: Props) {
  return (
    <QueryClientProvider client={queryClient}>
      {children(() => props.children)}
    </QueryClientProvider>
  );
}

// examples/react-standard/src/context.tsx
import { PropsWithChildren } from "react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { AuthProvider } from "@/modules/authentication";
import { CounterProvider } from "@/modules/count-context";

export const AppProviders = ({ children }: PropsWithChildren) => (
  <>
    <QueryClientProvider client={new QueryClient()}>
      <AuthProvider>
        <CounterProvider initialCount={10}>{children}</CounterProvider>
      </AuthProvider>
    </QueryClientProvider>
  </>
);
