// examples/nextjs-mini/src/components/theme-toggle.tsx
import { useEffect, useState } from "react";
import classes from "./theme-toggle.module.css";

type Props = {
  name: string;
};
export function ThemeToggle(props: Props) {
  const [isDarkMode, setIsDarkMode] = useState(false);

  useEffect(() => {
    isDarkMode
      ? document.body.classList.add("dark-scheme")
      : document.body.classList.remove("dark-scheme");
  }, [isDarkMode]);

  useEffect(() => {
    const handleChange = (e: MediaQueryListEvent) => setIsDarkMode(e.matches);
    const matchMedia = window.matchMedia("(prefers-color-scheme: dark)");
    matchMedia.addEventListener("change", handleChange);
    return () => matchMedia.removeEventListener("change", handleChange);
  }, []);

  const toggle = () => setIsDarkMode((s) => !s);

  return (
    <>
      <div className={classes.wrapper}>
        <h1 aria-label={props.name}>Getting started with {props.name}</h1>
        <button className={classes.button} role="button" onClick={toggle}>
          Click to switch {isDarkMode ? "light" : "dark"} mode
        </button>
      </div>
      <style global jsx>{`
        /* Dark theme CSS */
        :root {
          --light-color: #fcfbfb;
          --light-shadow-color: hsl(70deg 0% 85%);
          --dark-color: #24292f;
          --dark-shadow-color: hsl(0deg 10% 5%);

          color-scheme: light dark;
        }

        @media (prefers-color-scheme: dark) {
          :root {
            --color: var(--light-color);
            --background-color: var(--dark-color);
            --shadow-color: var(--dark-shadow-color);
          }
        }

        body.dark-scheme {
          --color: var(--light-color);
          --background-color: var(--dark-color);
          --shadow-color: var(--dark-shadow-color);
        }

        body {
          --color: var(--dark-color);
          --background-color: var(--light-color);
          --shadow-color: var(--light-shadow-color);

          color: var(--color);
          background-color: var(--background-color);
        }
      `}</style>
    </>
  );
}

// examples/vue-mini/src/components/theme-toggle.vue
<script setup lang="ts">
import { ref, watchEffect, onMounted, onUnmounted } from "vue";

const matchMedia = window.matchMedia("(prefers-color-scheme: dark)");

defineProps<{ name: string }>();

const isDarkMode = ref(matchMedia.matches);

function handleChange(event: MediaQueryListEvent) {
  isDarkMode.value = event.matches;
}

onMounted(() => matchMedia.addEventListener("change", handleChange));
onUnmounted(() => matchMedia.removeEventListener("change", handleChange));

watchEffect(() => {
  isDarkMode.value
    ? document.body.classList.add("dark-scheme")
    : document.body.classList.remove("dark-scheme");
});
</script>

<template>
  <div className="wrapper">
    <h1 :aria-label="name">Getting started with {{ name }}</h1>
    <button className="button" role="button" @click="isDarkMode = !isDarkMode">
      <span>Click to switch {{ isDarkMode ? "light" : "dark" }} mode</span>
    </button>
  </div>
</template>

<style>
/* Dark theme CSS */
:root {
  --light-color: #fcfbfb;
  --light-shadow-color: hsl(70deg 0% 85%);
  --dark-color: #24292f;
  --dark-shadow-color: hsl(0deg 10% 5%);

  color-scheme: light dark;
}

@media (prefers-color-scheme: dark) {
  :root {
    --color: var(--light-color);
    --background-color: var(--dark-color);
    --shadow-color: var(--dark-shadow-color);
  }
}

body.dark-scheme {
  --color: var(--light-color);
  --background-color: var(--dark-color);
  --shadow-color: var(--dark-shadow-color);
}

body {
  --color: var(--dark-color);
  --background-color: var(--light-color);
  --shadow-color: var(--light-shadow-color);

  color: var(--color);
  background-color: var(--background-color);
}
</style>

<style scoped>
/* Component CSS */
.wrapper {
  display: grid;
  min-height: 100vh;
  grid-template-columns: 1fr min(60ch, 90%) 1fr;
  place-content: center;
}

.wrapper > * {
  text-align: center;
  grid-column: 2;
}

h1 {
  font-size: 4rem;
  cursor: pointer;
  white-space: nowrap;
  display: flex;
  align-items: center;
  justify-content: center;
  line-height: 1.4;
  gap: 8px;
  letter-spacing: -0.03em;
  margin-bottom: 1.5rem;
}

/* Copied from https://getcssscan.com/css-buttons-examples */
.button {
  appearance: none;
  background-color: #2ea44f;
  border: 1px solid rgba(27, 31, 35, 0.15);
  border-radius: 6px;
  box-shadow: rgba(27, 31, 35, 0.1) 0 1px 0;
  box-sizing: border-box;
  color: #fff;
  cursor: pointer;
  display: inline-block;
  font-size: 14px;
  font-weight: 600;
  line-height: 20px;
  padding: 6px 16px;
  position: relative;
  text-align: center;
  text-decoration: none;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
  vertical-align: middle;
  white-space: nowrap;
}

.button:focus:not(:focus-visible):not(.focus-visible) {
  box-shadow: none;
  outline: none;
}

.button:hover {
  background-color: #2c974b;
}

.button:focus {
  box-shadow: rgba(46, 164, 79, 0.4) 0 0 0 3px;
  outline: none;
}

.button:disabled {
  background-color: #94d3a2;
  border-color: rgba(27, 31, 35, 0.1);
  color: rgba(255, 255, 255, 0.8);
  cursor: default;
}

.button:active {
  background-color: #298e46;
  box-shadow: rgba(20, 70, 32, 0.2) 0 1px 0 inset;
}
</style>
