// examples/solid-module-api-graphql/src/components/user-view.tsx
import { useUser } from "../hooks/use-user";
import { Match, Switch } from "solid-js";

export function UserView() {
  const query = useUser();

  return (
    <Switch>
      <Match when={query.isLoading}>
        <span aria-label="loading">Loading...</span>
      </Match>
      <Match when={query.isError}>
        <span aria-label="error">Error</span>
      </Match>
      <Match when={query.isSuccess}>
        <h2>{query.data?.user.name}</h2>
      </Match>
    </Switch>
  );
}

// examples/react/module-api-restful/src/components/user-view.tsx
import { useUser } from "../hooks/use-user";

export function UserView({ id }: { id: string }) {
  const { isLoading, isError, data } = useUser(id);

  if (isLoading) return <span aria-label="loading">Loading...</span>;
  if (isError) return <span aria-label="error">Error</span>;
  if (!data) return <span>No data!</span>;

  return <h2>{data.name}</h2>;
}
