// examples/solid-mini/src/routes.tsx
import { lazy } from "solid-js";
import type { RouteDefinition } from "@solidjs/router";

const routes: RouteDefinition[] = [
  {
    path: "/",
    component: lazy(() => import("@/pages/home")),
  },
  {
    path: "**",
    component: lazy(() => import("@/pages/not-found")),
  },
];
export default routes;

// examples/react-mini/src/routes.tsx
import { lazy } from "react";
import { Switch, Route } from "wouter";

const Home = lazy(() => import("@/pages/home"));
const NotFound = lazy(() => import("@/pages/not-found"));

const routes = () => (
  <Switch>
    <Route path="/">
      <Home />
    </Route>
    <Route>
      <NotFound />
    </Route>
  </Switch>
);
export default routes;
