// examples/react-mini/src/routes.tsx
import { lazy } from "react";
import { Switch, Route } from "wouter";

const Home = lazy(() => import("@/pages/home"));
const NotFound = lazy(() => import("@/pages/not-found"));

const routes = () => (
  <Switch>
    <Route path="/">
      <Home />
    </Route>
    <Route>
      <NotFound />
    </Route>
  </Switch>
);
export default routes;

// code/solid/base/src/routes.tsx
import { Routes, Route } from "@solidjs/router";
import { lazy, JSXElement, children } from "solid-js";
import { Layout } from "@/ui/pages/layout";

const Home = lazy(() => import("@/ui/pages/index"));
const About = lazy(() => import("@/ui/pages/about"));
const NotFound = lazy(() => import("@/ui/pages/not-found"));

type Props = {
  children: JSXElement;
};
function WithLayout(props: Props) {
  return <Layout>{children(() => props.children)}</Layout>;
}

const routes = () => {
  return (
    <Routes>
      <Route
        path="/about"
        element={
          <WithLayout>
            <About />
          </WithLayout>
        }
      />
      <Route
        path="/"
        element={
          <WithLayout>
            <Home />
          </WithLayout>
        }
      />
      <Route path="/**" component={NotFound} />
    </Routes>
  );
};

export default routes;
