// examples/solid-base-2/src/context.tsx
import { children, JSXElement } from "solid-js";
import { QueryClient, QueryClientProvider } from "@tanstack/solid-query";

const queryClient = new QueryClient();

type Props = { children: JSXElement };

export function AppProviders(props: Props) {
  return (
    <QueryClientProvider client={queryClient}>
      {children(() => props.children)}
    </QueryClientProvider>
  );
}

// code/react/base/src/context.tsx
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { PropsWithChildren } from "react";

const queryClient = new QueryClient();

export function AppProviders({ children }: PropsWithChildren) {
  return (
    <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
  );
}
